# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Minitun < Formula
  desc "CLI-first sing-box manager with daemon mode for macOS"
  homepage "https://github.com/shrektan/minitun"
  version "0.1.2"
  license "MIT"

  depends_on "fzf"
  depends_on "sing-box"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/shrektan/minitun/releases/download/v0.1.2/minitun_0.1.2_darwin_amd64.tar.gz"
    sha256 "c122a8c236364c400be838c0204ad407eb256ff93f172eac4dbf6660757a064b"

    def install
      bin.install "minitun"
      bin.install "minitund"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/shrektan/minitun/releases/download/v0.1.2/minitun_0.1.2_darwin_arm64.tar.gz"
    sha256 "6bbc31aba46554036ab26260acc86164b20c42900fd636b1da73b63ae450e849"

    def install
      bin.install "minitun"
      bin.install "minitund"
    end
  end

  test do
    system "#{bin}/minitun", "help"
  end
end
